language: csharp
solution: FxCommon.sln
dotnet: 1.1.5
install:
  - nuget restore FxCommonStandard.sln
script:
  - dotnet restore
  - dotnet build
  - dotnet test /home/travis/build/waldrix/FxCommonStandard/FxCommonStandard.Tests/bin/Debug/netcoreapp1.1/FxCommonStandard.Tests.dll
